name = "star-path-viewer"
compatibility_date = "2026-04-19"
pages_build_output_dir = "dist"

[vars]
YARN_VERSION = 4
NODE_VERSION = "24.14.0"
CI = true
GENERATE_SOURCEMAP = false
VITE_APP_NAME = "Star Path Viewer"
VITE_EMAIL = "stardial.astro@gmail.com"
VITE_GA_ID = "G-WRBP5P612C"
VITE_IS_PREVIEW = false
VITE_SERVER_URL = "https://teststarpathcalculator.pythonanywhere.com/"
VITE_NOMINATIM_SEARCH_URL = "https://nominatim.openstreetmap.org/search"
VITE_NOMINATIM_REVERSE_URL = "https://nominatim.openstreetmap.org/reverse"
VITE_SEARCH_SERVICE_CN = "Baidu"
VITE_REVERSE_SERVICE_CN = "Tianditu"

[env.preview.vars]
VITE_IS_PREVIEW = true
