name: React Tests

on:
  push:
    branches:
      - cloudflare-deploy
  pull_request:
    branches:
      - cloudflare-deploy

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Run tests
      run: yarn test

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.yarn/cache
          ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
